-- 모든 컬럼 순서데로 값 넣기
INSERT INTO EMP values(1000, 'SMITH', 'ACCOUNTING', DATE('23/02/13'), NULL, 20 );

INSERT INTO EMP values(1001, 'SALLY', 'ACCOUNTING', NOW(), NULL, 20 );

INSERT INTO EMP values(1002, 'EMILLY','SELLER', NOW(), 500, 21);


-- 지정한 컬럼만 값 넣기
INSERT INTO EMP (EMPNO, ENAME, HIREDATE) VALUES(1001, 'SALLY', now());

-- 테이블구조/데이터 카피
CREATE TABLE EMP_COPY SELECT * FROM EMP e ;

-- 데이터 지우기
TRUNCATE TABLE EMP_COPY;

-- 데이터 수정
UPDATE EMP SET ENAME = 'STOMMY', JOB = 'PROJECT LEADER' WHERE EMPNO = 1000;

-- 데이터 삭제
DELETE FROM EMP WHERE EMPNO = 1001;

-- 컬럼 별칭 사용하여 출력
SELECT EMPNO NO, ENAME NAME FROM EMP WHERE empno = 1000;

-- BETWEEN 조건문
SELECT EMPNO, ENAME FROM EMP WHERE EMPNO BETWEEN 1000 AND 1001;

-- IN 조건문
SELECT EMPNO, ENAME FROM EMP WHERE EMPNO IN (1001);

-- LIKE 조건문
SELECT EMPNO, ENAME FROM EMP WHERE JOB LIKE 'SELLER';
-- LIKE : % 여러개 문자열
SELECT EMPNO, ENAME FROM EMP WHERE JOB LIKE '%LEADER';
-- LIKE : _ 하나의 문자
SELECT EMPNO, ENAME FROM EMP WHERE ENAME LIKE '__LLY';
-- LIKE : ESCAPE 와일드 카드 문자를 일반 문자처럼 사용
SELECT EMPNO, ENAME FROM EMP WHERE ENAME LIKE '%LLY' ESCAPE '%';
-- LIKE : UPPER 대소문자 구분없이 출력
SELECT EMPNO, ENAME FROM EMP WHERE UPPER(ENAME) LIKE '%lly';

-- IS NULL 조건문
SELECT EMPNO, ENAME FROM EMP WHERE SAL IS NULL;

-- NOT BEETWEEN
SELECT EMPNO, ENAME FROM EMP WHERE EMPNO NOT BETWEEN 1000 AND 1001;

-- NOT IN
SELECT EMPNO, ENAME FROM EMP WHERE DEPNO NOT IN (19, 20, 21);

-- NOT LIKE
SELECT EMPNO, ENAME FROM EMP WHERE DEPNO NOT LIKE 20;

-- IS NOT NULL
SELECT EMPNO, ENAME FROM EMP WHERE SAL IS NOT NULL;

-- ORDER BY
SELECT EMPNO, ENAME, JOB FROM EMP WHERE JOB IS NOT NULL ORDER BY JOB;

-- 테이블 예명
SELECT DEPNO DEP, COUNT(DEPNO) CNT FROM EMP GROUP BY DEPNO;


