--조건에 맞는 도서와 저자 리스트 출력하기
SELECT B.BOOK_ID, 
       A.AUTHOR_NAME,
       TO_CHAR(B.PUBLISHED_DATE, 'YYYY-MM-DD') PUBLISHED_DATE
  FROM BOOK B
  LEFT JOIN AUTHOR A
    ON A.AUTHOR_ID = B.AUTHOR_ID
 WHERE B.CATEGORY = '경제'
 ORDER BY PUBLISHED_DATE